package com.justinquinnb.onefeed.customization.textstyle;

import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * A {@link Set} of {@link FormattingRule}s in the desire order of application to a marked-up {@code String}.
 * @param <T> the language that the {@link TextFormatting} contained in the {@link FormattingMarkedText} generated by
 *           one of {@code this} ruleset's {@code FormattingRule}s
 */
public class FormattingRuleset<T extends TextFormatting> implements Iterable<FormattingRule<T>> {
    /**
     * The {@link Set} of {@link FormattingRule}s to apply on some marked-up text in the order that they appear in the
     * {@code Set}.
     */
    private LinkedHashSet<FormattingRule<T>> rules;

    @Override
    public Iterator<FormattingRule<T>> iterator() {
        return this.rules.iterator();
    }
}